# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
   
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 lighthouse-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.0
    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@v12.0.1
      with:
        urls: 'https://mitesh411.github.io/MyResume/'
    - name: Upload artifacts
      uses: actions/upload-artifact@v4.4.0
      with:
        name: Lighthouse reports
        path: ${{ github.workspace }}/tmp/artifacts
   
